#!/bin/sh

NAME="twitter"
DJANGODIR=/home/robertozarzur/twitter_me/twitter_me_project
SOCKFILE=/home/robertozarzur/twitter_me/run/gunicorn.sock
USER=oinkuser
GROUP=oinkgroup
NUM_WORKERS=3
DJANGO_SETTINGS_MODULE=twitter.settings
DJANGO_WSGI_MODULE=twitter.wsgi
TIMEOUT=120

cd $DJANGODIR
source ../bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

exec ../bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --timeout $TIMEOUT \
  --user=$USER --group=$GROUP \/home/robertozarzur/twitter_me/twitter_me_project
  --bind=unix:$SOCKFILE \
  --log-level=debug \
  --log-file=-
